
name: manager_mobile_client
version: 1.26.1+64

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  file: ^6.1.4
  collection: ^1.17.0
  http: ^1.3.0
  web_socket_channel: ^2.4.0
  path: ^1.8.2
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  url_launcher: ^6.1.11
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.3.0
  image_picker: ^1.0.4

  tuple: ^2.0.2
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  geocoding: ^3.0.0


#  flutter_app_badger: ^1.5.0
  audioplayers: ^6.3.0
  photo_view: ^0.15.0
  mason: ^0.1.0-dev.50
  intl: ^0.19.0
  flutter_bloc: ^9.0.0
  go_router: ^14.8.1
  geohash_plus: ^1.1.1
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  assets:
  - lib/l10n/
  - assets/images/menu/
  - assets/images/map/
  - assets/images/markers/
  - assets/sounds/notification.mp3
  uses-material-design: true
