// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz1mWfxKTHuTFTJouQRdufkDLtKiUZmXI',
    appId: '1:598544058294:web:362b01b56e77c034bc6317',
    messagingSenderId: '598544058294',
    projectId: 'cargodeal-14936',
    authDomain: 'cargodeal-14936.firebaseapp.com',
    storageBucket: 'cargodeal-14936.firebasestorage.app',
    measurementId: 'G-5BY6G2N5TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWGHVGeq92rq0WVAJLCWNU5hLEqocXg8c',
    appId: '1:598544058294:android:0e55c352bd4104dbbc6317',
    messagingSenderId: '598544058294',
    projectId: 'cargodeal-14936',
    storageBucket: 'cargodeal-14936.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6jG1FTFRYMjyuOon7deIOmkOi_YxsR4c',
    appId: '1:598544058294:ios:21381e4d2644abe6bc6317',
    messagingSenderId: '598544058294',
    projectId: 'cargodeal-14936',
    storageBucket: 'cargodeal-14936.firebasestorage.app',
    iosBundleId: 'com.dnlabs.cargoclient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6jG1FTFRYMjyuOon7deIOmkOi_YxsR4c',
    appId: '1:598544058294:ios:2ac4bc7b44f77ca1bc6317',
    messagingSenderId: '598544058294',
    projectId: 'cargodeal-14936',
    storageBucket: 'cargodeal-14936.firebasestorage.app',
    iosBundleId: 'com.example.cargoClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz1mWfxKTHuTFTJouQRdufkDLtKiUZmXI',
    appId: '1:598544058294:web:90d3a00749924464bc6317',
    messagingSenderId: '598544058294',
    projectId: 'cargodeal-14936',
    authDomain: 'cargodeal-14936.firebaseapp.com',
    storageBucket: 'cargodeal-14936.firebasestorage.app',
    measurementId: 'G-RV0MRRG990',
  );
}
